title: "Lei Liu @ University of Colorado Boulder"
author: "LEI LIU"
description: "University of Colorado Boulder"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site; false
show_sidebar: false        # show a sidebar instead of the usual header; false
show_social: true          # show site description and social links in the footer
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
#   - {file: "index.md"}
#   - {file: "people.md", title: "People"}
  - {file: "research.md", title: "Research"}
  - {file: "participate.md", title: "Participate"}
  - {file: "resources.md", title: "Resources"}
  - {file: "publications.md", title: "Publications"}
  - {file: "life.md", title: "Life"}
#   - {file: "participate.md", title: "Participate"}

# %%%
#   - {file: "index.md"}
#   - {file: "people.md", title: "People"}
#   - {file: "research.md", title: "Research"}
#   - {file: "participate.md", title: "Participate"}
#   - {file: "resources.md", title: "Resources"}
# %%%

# collections
collections:
  authors:
    output: true
    
# categories for authors page
categories-order:
 - Paper
 - Grant
 - Talk
 - Poster
 - News

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:lei.liu@colorado.edu"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Liu-Lei-16"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0002-1040-6026"}
  - {title: GOOGLE, icon: google, url: "https://scholar.google.com/citations?user=JqwKipIAAAAJ&hl=en"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/lei-liu-46b551222/"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
#   - {title: Subscribe, icon: rss, url: "/feed.xml"} # Subscribe

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

remote_theme: niklasbuschmann/contrast@v2.11
# remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
